### ISSUE TITLE
New docs layout

### ISSUE THREAD

**Issue by LostNeophyte** [LunarVim/lunarvim.org#352]
## Plan for a new layout:
```markdown
# Installation
  - [new] Post install ($PATH, nerd fonts)
# Beginner's guide
  - [new] Terminology (what's LSP, treesitter, autocmds)
  - [new] Plugins overview (most important ones)
  - Keybinds overview  
# Configuration
  - [new] Options (vim.opt, vim.g)
  - Keybindings
  - Plugins
    - [new] Core plugins (lvim.builtin)
    - [new] User plugins (lvim.plugins)
    - Example configurations (current `plugins/extra-plugins.md`)
  - Appearance (no readme.md)
    - Colorschemes
    - Statusline
  - LSP (current `languages/README.md`) TODO: better name for the section
  - Snippets
  - Autocommands
  - Ftplugin
# [new/needs update] FAQ
# Troubleshooting
# Features
  - Supported languages (current languages)
    - ...
  - Supported frameworks (current frameworks)
    - ...
# community
  - Meet the team
```
## todo list
- [ ] Post install (https://github.com/LunarVim/lunarvim.org/pull/353)
- [ ] Terminology
- [ ] Plugins overview
- [ ] Options (vim.opt, vim.g)
- [ ] Core plugins (lvim.builtin)
- [ ] User plugins (lvim.plugins)
- [ ] Appearance
- [ ] LSP
- [ ] FAQ

fixes #217, #251

**Comment by apoorvapendse** [comment]
Can i help you write the plugins overview?

**Comment by LostNeophyte** [comment]
@apoorvapendse 
it's already written in the master version of the docs (https://www.lunarvim.org/docs/master/beginners-guide/plugins-overview)
however it does have an error, NERDtree is in there, it should be nvimtree. you can improve the page if you want, I intended it to be mostly for ui plugins so that a new user know what they're looking at
thanks

**Comment by apoorvapendse** [comment]
you mean just the typo?

**Comment by LostNeophyte** [comment]
typo and whatever you want

**Comment by apoorvapendse** [comment]
alright i'll create a PR in 5 mins

**Comment by apoorvapendse** [comment]
done #424

**Comment by etleyden** [comment]
For the plugins overview, does anyone think there should be links to those repositories, so readers can see more documentation on those plugins?

**Comment by arthuralcorrea** [comment]
In my opinion `plugins overview` is redundant, since we already have the main references in `keybinds-overview`
